### ISSUE TITLE
Feature Idea - Global TakeUntil

### ISSUE THREAD

**Issue by warmans** [flowup/api-client-generator#52]
So the situation is you have a page which contains a bunch of components that might be executing API requests at any time. You then have an event that means you need to just kill everything and take the user somewhere else (e.g. their token expired and you just want to take them back to a login page).

So the current way to do this is to have a `ngDestroy` on each component that handles the cancellation of the request either by directly unsubscribing or managing a local takeUntil.

But I think it would be possible to implement a generic solution to this since `takeUntil` is implemented before subscribe so the generated `sendRequest` method could just attach a `takeUntil` to all observables allowing api requests to be globally cancelled via a single event emitter.

Or something like - if an emitter is injected then it adds the takeUntil otherwise it just does the normal thing.

What do you think?

**Comment by vmasek** [comment]
Just to be certain, you mean the use case when you have called an API, haven't got the response yet (because it takes for a few seconds) and redirect to another component which doesn't need the data from the last call?

Http Observables are completed after they receive a response automatically and there is [no need to unsubscribe](https://stackoverflow.com/questions/35042929/ist-it-necessary-to-unsubscribe-from-observables-created-by-http-methods)

If we get back to the use case of canceling a call. There might be a problem how to handle the call purpose, I can see that sometimes it might be useful to cancel for example `getAllProducs` but with the global take until it might also cancel useful call like `postProduct` or `addToCart`.
Also if we consiger having a state management in project, these calls are usualy handled in effects where we don't want any calls to cancel because even after redirecting to other component, we want the actions from previouse one to be completed and reflected in store.

**Comment by warmans** [comment]
Yeah exactly, when there are several in-flight requests (or pending) that you just want to abandon and prevent from hitting any interceptors or child subscriptions.

You're right though - non-idempotent requests are a bit problematic. Perhaps it's not something that could be done in a generic way.

**Comment by vmasek** [comment]
Yes, it might be a nice feature, but when adding stuff like this, we must be careful about the correct use case. I wouldn't be glad to see bugs when someone uses it incorrectly because we let them do it :smile: 

After all, it can be handled the way you handle in service/component pretty easily

**Comment by DeeNeon** [comment]
Thanks @vmasek I'll check, I actually exported it from Stoplight, and indeed it's invalid... sigh.
Cheers!
